// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(HouseDbContext))]
    [Migration("20250409093534_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("HouseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .HasColumnType("TEXT");

                    b.Property<int>("price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            Country = "USA",
                            Description = "Beautiful house in the city",
                            Photo = "house1.jpg",
                            price = 300000
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St",
                            Country = "USA",
                            Description = "Spacious house with a garden",
                            Photo = "house2.jpg",
                            price = 400000
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Oak St",
                            Country = "USA",
                            Description = "Modern house with a pool",
                            Photo = "house3.jpg",
                            price = 500000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
